name: clique
description: Implementation of the Bron–Kerbosch maximal cliques algorithm in Dart
version: 1.0.1
repository: https://github.com/dancarroll/dart_clique
issue_tracker: https://github.com/dancarroll/dart_clique/issues

environment:
  sdk: ^3.6.0

dependencies:


dev_dependencies:
  benchmark_harness: ^2.3.1
  lints: ^5.0.0
  test: ^1.24.0
